### ISSUE TITLE
Esta repetido o que on da?

### ISSUE THREAD

**Issue by victorsada** [victorsada/gasto-semanal#8]
https://github.com/victorsada/gasto-semanal/blob/22ecad27c00aba42f8657eb8a9cfdf6ccf29bfdf/src/index.js#L19

Puede ser que la linea 19 y la 21 esten repetidas? please fix it ;)

**Comment by SalomonSada** [comment]
si, hay que sustituir en la linea 19 gasto por auth, arreglado
